### ISSUE TITLE
Formula expansion in nested blocks 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/xlsx-datafill#13]
Formula expansion on first block (marked green) is working fine.
The formula expansion in the next block on the right (marked orange) are not correct - they point to columns in the first block.  
Ideally, the blue lines should contain formula expansion for the corresponding blocks , though I don;t expect it to work at the moment)
[formula.xlsx](https://github.com/ideaconsult/xlsx-datafill/files/4455988/formula.xlsx)

**Comment by thejonan** [comment]
Fixed by #14
